name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run 'Liquibase status' in a Docker Container for DEV
        uses: docker://liquibase/liquibase:latest
        with:
          args: status --url=${{ secrets.DEV_URL }} --changeLogFile=/root/db/changelog/changelog-root.xml --username=${{ secrets.SF_USERNAME }} --password=${{ secrets.SF_PASSWORD }} --driver=${{ secrets.SF_DRIVER }} --defaultsFile=liquibase.properties
      - name: Run 'Liquibase update' in a Docker Container for DEV
        uses: docker://liquibase/liquibase:latest
        with:
          args: update --url=${{ secrets.DEV_URL }} --changeLogFile=/root/db/changelog/changelog-root.xml --username=${{ secrets.SF_USERNAME }} --password=${{ secrets.SF_PASSWORD }} --driver=${{ secrets.SF_DRIVER }} --defaultsFile=liquibase.properties

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run 'Liquibase status' in a Docker Container for TEST
        uses: docker://liquibase/liquibase:latest
        with:
          args: status --url=${{ secrets.TEST_URL }} --changeLogFile=/root/db/changelog/changelog-root.xml --username=${{ secrets.SF_USERNAME }} --password=${{ secrets.SF_PASSWORD }} --driver=${{ secrets.SF_DRIVER }} --defaultsFile=liquibase.properties
      - name: Run 'Liquibase update' in a Docker Container for TEST
        uses: docker://liquibase/liquibase:latest
        with:
          args: update --url=${{ secrets.TEST_URL }} --changeLogFile=/root/db/changelog/changelog-root.xml --username=${{ secrets.SF_USERNAME }} --password=${{ secrets.SF_PASSWORD }} --driver=${{ secrets.SF_DRIVER }} --defaultsFile=liquibase.properties