name: CI

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deployment-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v4
      - name: Run 'Liquibase tag' in a Docker Container for DEV
        #run: echo ${{ github.head_ref }}, ${{ github.ref }}, ${{ github.ref_name }}, ${{ github.ref_type }}
        uses: docker://liquibase/liquibase:latest
        with:
          args: tag --url=${{ vars.DEV_URL }} --tag=${{ github.head_ref }}_Dev --username=${{ vars.USERNAME}} --password=${{ secrets.SF_PASSWORD }} --defaultsFile=liquibase.properties
      - name: Run 'Liquibase status' in a Docker Container for DEV
        uses: docker://liquibase/liquibase:latest
        with:
          args: status --url=${{ vars.DEV_URL }} --username=${{ vars.USERNAME}} --password=${{ secrets.SF_PASSWORD }} --context-filter=DEV --defaultsFile=liquibase.properties
      - name: Run 'Liquibase update SQL' in a Docker Container for DEV
        uses: docker://liquibase/liquibase:latest
        with:
          args: update-sql --url=${{ vars.DEV_URL }} --username=${{ vars.USERNAME}} --password=${{ secrets.SF_PASSWORD }} --context-filter=DEV --defaultsFile=liquibase.properties
      - name: Run 'Liquibase update with rollback' in a Docker Container for DEV
        uses: docker://liquibase/liquibase:latest
        with:
          args: update-testing-rollback --url=${{ vars.DEV_URL }} --username=${{ vars.USERNAME}} --password=${{ secrets.SF_PASSWORD }} --context-filter=DEV --defaultsFile=liquibase.properties

  deployment-test:
    needs: deployment-dev
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - uses: actions/checkout@v4
      - name: Run 'Liquibase tag' in a Docker Container for DEV
        #run: echo ${{ github.head_ref }}, ${{ github.ref }}, ${{ github.ref_name }}, ${{ github.ref_type }}
        uses: docker://liquibase/liquibase:latest
        with:
          args: tag --url=${{ vars.TEST_URL }} --tag=${{ github.head_ref }}_Test --username=${{ vars.USERNAME}} --password=${{ secrets.SF_PASSWORD }} --defaultsFile=liquibase.properties
      - name: Run 'Liquibase status' in a Docker Container for TEST
        uses: docker://liquibase/liquibase:latest
        with:
          args: status --url=${{ vars.TEST_URL }} --username=${{ vars.USERNAME}} --password=${{ secrets.SF_PASSWORD }} --context-filter=TEST --defaultsFile=liquibase.properties
      - name: Run 'Liquibase update SQL' in a Docker Container for DEV
        uses: docker://liquibase/liquibase:latest
        with:
          args: update-sql --url=${{ vars.TEST_URL }} --username=${{ vars.USERNAME}} --password=${{ secrets.SF_PASSWORD }} --context-filter=TEST --defaultsFile=liquibase.properties
      - name: Run 'Liquibase update' in a Docker Container for TEST
        uses: docker://liquibase/liquibase:latest
        with:
          args: update --url=${{ vars.TEST_URL }} --username=${{ vars.USERNAME}} --password=${{ secrets.SF_PASSWORD }} --context-filter=TEST --defaultsFile=liquibase.properties