name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deployment-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v4
      ##- name: Run 'Liquibase tag' in a Docker Container for DEV
        ##  uses: docker://liquibase/liquibase:latest
          ## with:
        ##  args: tag --url=${{ env.DEV_URL }} --tag=${{ github.ref }} --username=${{ env.USERNAME }} --password=${{ secrets.SF_PASSWORD }}  --driver=${{ env.DRIVER }} --defaultsFile=liquibase.properties
      - name: Run 'Liquibase status' in a Docker Container for DEV
        uses: docker://liquibase/liquibase:latest
        with:
          args: status --url=${{ env.DEV_URL }} --changeLogFile=/root/db/changelog/changelog-root.xml --username=${{ env.USERNAME }} --password=${{ secrets.SF_PASSWORD }}  --driver=${{ env.DRIVER }} --defaultsFile=liquibase.properties
      - name: Run 'Liquibase update SQL' in a Docker Container for DEV
        uses: docker://liquibase/liquibase:latest
        with:
          args: update-sql --url=${{ env.DEV_URL }} --changeLogFile=/root/db/changelog/changelog-root.xml --username=${{ env.USERNAME }} --password=${{ secrets.SF_PASSWORD }}  --driver=${{ secrets.DRIVER }} --context-filter=DEV --defaultsFile=liquibase.properties
      - name: Run 'Liquibase update with rollback' in a Docker Container for DEV
        uses: docker://liquibase/liquibase:latest
        with:
          args: update-testing-rollback --url=${{ env.DEV_URL }} --changeLogFile=/root/db/changelog/changelog-root.xml --username=${{ env.USERNAME }} --password=${{ secrets.SF_PASSWORD }}  --driver=${{ secrets.DRIVER }} --context-filter=DEV --defaultsFile=liquibase.properties

  deployment-test:
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - uses: actions/checkout@v4
      - name: Run 'Liquibase tag' in a Docker Container for TEST
        uses: docker://liquibase/liquibase:latest
        with:
          args: tag --url=${{ env.TEST_URL }} --tag=${{ github.ref_name }} --username=${{ env.USERNAME }} --password=${{ secrets.SF_PASSWORD }}  --driver=${{ env.DRIVER }} --defaultsFile=liquibase.properties
      - name: Run 'Liquibase status' in a Docker Container for TEST
        uses: docker://liquibase/liquibase:latest
        with:
          args: status --url=${{ env.TEST_URL }} --changeLogFile=/root/db/changelog/changelog-root.xml --username=${{ env.USERNAME }} --password=${{ secrets.SF_PASSWORD }}  --driver=${{ env.DRIVER }} --defaultsFile=liquibase.properties
      - name: Run 'Liquibase update SQL' in a Docker Container for DEV
        uses: docker://liquibase/liquibase:latest
        with:
          args: update-sql --url=${{ env.TEST_URL }} --changeLogFile=/root/db/changelog/changelog-root.xml --username=${{ env.USERNAME }} --password=${{ secrets.SF_PASSWORD }}  --driver=${{ secrets.DRIVER }} --context-filter=TEST --defaultsFile=liquibase.properties
      - name: Run 'Liquibase update' in a Docker Container for TEST
        uses: docker://liquibase/liquibase:latest
        with:
          args: update --url=${{ env.TEST_URL }} --changeLogFile=/root/db/changelog/changelog-root.xml --username=${{ env.USERNAME }} --password=${{ secrets.SF_PASSWORD }}  --driver=${{ secrets.DRIVER }} --context-filter=TEST --defaultsFile=liquibase.properties