name: CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deployment-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v4

      - name: URL encode private key
        id: encode-key
        run: echo "ENCODED_PRIVATE_KEY=$(echo -n '${{ secrets.SSL_PRIVATEKEY }}' | sed ':a;N;$!ba;s/\n//g' | jq -sRr @uri)" >> $GITHUB_ENV

      - name: Print encoded private key (for debugging)
        run: echo "${{ env.ENCODED_PRIVATE_KEY }}"

      - name: Run 'Liquibase status' in a Docker Container for DEV
        uses: docker://liquibase/liquibase:latest
        with:
          args: --log-level=FINE status --url="jdbc:snowflake://YQQTDYK-CLARIVATEDATASVS.snowflakecomputing.com/?db=CICD_LIQUIBASE&schema=PUBLIC&user=CICD_SERVICE_ACCOUNT&private_key=${{ env.ENCODED_PRIVATE_KEY }}" --context-filter=DEV --defaultsFile=liquibase.properties